### ISSUE TITLE
Exercise 15.1 derivation mistake

### ISSUE THREAD

**Issue by martinjurkovic** [fri-datascience/course_pou#2]
There is a mistake when derivating the MLE of variance in exercise 15.1.

When derivating the second term there should be a minus in the exponent (see attached image, the exponent with the blue box should have a minus).

<img width="939" alt="image" src="https://user-images.githubusercontent.com/45878038/216316460-62fbd826-3d44-4b3d-ac93-03d770eb4953.png">

**Comment by LeonHvastja** [comment]
Fixed
